### PR TITLE
Review 1: Eslint Fix | TxDecoder | OfflineSigning | IBCLightClient.ClientState 

### LINKED ISSUE #308: Problem: TxDecoder is missing slashing and IBC transactions

### LINKED ISSUE #310: Problem: Inconsistence of TxDecoer result with CosmosSDK

### LINKED ISSUE #314: Problem: `MsgCreateClient` proto type definitions & TxDecoding Support

### LINKED ISSUE #317: Problem: LightClient.ClientState support

### PR DESCRIPTION
**Pull request by cdc-Hitesh**
PR #311 

Fixes #317 
Fixes #314 
Fixes #310 
Fixes #308

### CODE REVIEW

File: lib/e2e/tx-decoder/compare.ts [hunk 1]
```diff
@@ -0,0 +1,122 @@
...
+
+            if (block.error) {
+                return Promise.reject(new Error('Exceeded chain latest height'));
+            }
+
+            return block.data.result.block.data.txs;
+        } catch (err) {
+            console.error(`error when requesting Tenderint RPC: ${err.toString()}. Retry in 1 minute`);
+            /* eslint-disable-next-line no-await-in-loop */
+            await new Promise((resolve) => setTimeout(resolve, 60000));
```
Comment (crypto-3dd) [inline lib/e2e/tx-decoder/compare.ts:50]: I'm somehow curious why wait for a whole minute, is there a reason behind that long wait time?

File: lib/src/transaction/amino.spec.ts [hunk 2]
```diff
@@ -108,7 +108,7 @@ describe('Amino JSON sign mode', function () {
                 accountSequence: new Big('1'),
                 signMode: SIGN_MODE.LEGACY_AMINO_JSON,
             })
-            .setFee(cro.Coin.fromBaseUnit('10000'))
+            .setFees([cro.v2.CoinV2.fromBaseUnit('10000')])
```
Comment (crypto-3dd) [inline lib/src/transaction/amino.spec.ts:111]: Was the old `setFee` removed? Does this impact the way we did previously transactions, I'm curious if backwards compatibility is preserved here.

File: lib/e2e/tx-decoder/compare.ts (hunk 1 above)
Comment (cdc-Hitesh) [reply lib/e2e/tx-decoder/compare.ts:50]: I am not sure but I think to avoid over-requesting the RPC server and letting the server re-settle up a few things.

Calvin can answer this precisely.

File: lib/src/transaction/amino.spec.ts (hunk 2 above)
Comment (cdc-Hitesh) [reply lib/src/transaction/amino.spec.ts:111]: This test case is a `v2` checker.
And yes `setFee` is marked deprecated in V2 RawTransaction.

The original `RawTransaction` still has the `setFee` function and here backwards compatibility is taken care off.

Still let me know your thought.

File: lib/src/transaction/v2.raw.ts [hunk 3]
```diff
@@ -168,16 +210,30 @@ export const rawTransactionV2 = function (config: InitConfigurations) {
         }
 
         /**
-         * Sets a `single` only fee amount to the raw tx
-         * @param {ICoin} feeAmount amount to be set to the raw tx body
-         * @returns {RawTransactionV2}
+         * Set fee to the raw tx
```
Comment (calvinaco) [inline lib/src/transaction/v2.raw.ts:213]:
```suggestion
         * Sets a `single` only fee amount to the raw tx
```

File: lib/src/transaction/msg/gov/proposal/SoftwareUpgradeProposal.spec.ts [hunk 4]
```diff
@@ -127,5 +127,34 @@ describe('Testing SoftwareUpgradeProposal and its content types', function () {
...
+                    "upgradedClientState": { "typeUrl": "someTypeUrl", "value": "someValue"}
+                }
+            }`;
+            const SoftwareUpgradeProposal = cro.gov.proposal.SoftwareUpgradeProposal.fromCosmosMsgJSON(json);
+
+            expect(SoftwareUpgradeProposal.title).to.eql('Text Proposal Title');
+
+            expect(SoftwareUpgradeProposal.description).to.eql('Lorem Ipsum ... Checking text proposal');
+            // @ts-ignore
+            expect(SoftwareUpgradeProposal.plan.upgradedClientState).to.be.undefined;
```
Comment (calvinaco) [inline lib/src/transaction/msg/gov/proposal/SoftwareUpgradeProposal.spec.ts:146]: Here should it throw instead of silently swallowing the `upgradedClientState`?

**Review by calvinaco — CHANGES_REQUESTED** [review]

File: lib/e2e/tx-decoder/compare.ts (hunk 1 above)
Comment (calvinaco) [reply lib/e2e/tx-decoder/compare.ts:50]: This retry is to handle the rate limit case and could be shorten, on our public RPC the rate limit is per n-minutes interval.

File: lib/src/utils/txDecoder.ts [hunk 5]
```diff
@@ -123,16 +125,89 @@ function decodeAnyType(typeUrl: string, value: Uint8Array) {
...
+        // Check if the `commission` object values are represented already in `float`
+        /*eslint-disable */
+        for (const key in decodedParams.commission) {
+            const rateString = decodedParams.commission[key];
+            const splitRateByDecimal = rateString.split('.');
+
+            // if `string` has `NO` decimal place
+            if (splitRateByDecimal.length === 1) {
+                const rateToBig = new Big(rateString);
+                clonedDecodedParams.commission[key] = rateToBig.div(new Big(1e18)).toFixed(18);
```
[the remark this answers is not in the document]
Comment (cdc-Hitesh) [reply lib/src/utils/txDecoder.ts:153]: Noted.
Better to be safe.

File: lib/src/utils/txDecoder.ts [hunk 6]
```diff
@@ -123,16 +125,89 @@ function decodeAnyType(typeUrl: string, value: Uint8Array) {
...
+            const splitRateByDecimal = rateString.split('.');
+
+            if (!splitRateByDecimal) {
+                clonedDecodedParams.commissionRate = null;
+            }
+
+            // if `string` has `NO` decimal place
+            if (splitRateByDecimal.length === 1) {
+                const rateToBig = new Big(rateString);
+                clonedDecodedParams.commissionRate = rateToBig.div(new Big(1e18)).toFixed(18);
```
[the remark this answers is not in the document]
Comment (cdc-Hitesh) [reply lib/src/utils/txDecoder.ts:174]: Noted.

File: lib/src/transaction/msg/gov/proposal/SoftwareUpgradeProposal.spec.ts (hunk 4 above)
Comment (cdc-Hitesh) [reply lib/src/transaction/msg/gov/proposal/SoftwareUpgradeProposal.spec.ts:146]: Actually `.plan.upgradedClientState` is an optional parameter, hence had to suppress the tslint error.

File: lib/src/utils/txDecoder.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (cdc-Hitesh) [reply lib/src/utils/txDecoder.ts]: Resolved.

File: lib/src/utils/txDecoder.ts (hunk 6 above)
[the remark this answers is not in the document]
Comment (cdc-Hitesh) [reply lib/src/utils/txDecoder.ts]: Resolved

File: lib/src/transaction/v2.raw.ts [hunk 7]
```diff
@@ -169,15 +211,29 @@ export const rawTransactionV2 = function (config: InitConfigurations) {
 
         /**
          * Sets a `single` only fee amount to the raw tx
-         * @param {ICoin} feeAmount amount to be set to the raw tx body
-         * @returns {RawTransactionV2}
+         * @param {ICoin} fee to be set to the raw tx body
+         * @returns {RawTransaction}
```
Comment (calvinaco) [inline lib/src/transaction/v2.raw.ts:215]:
```suggestion
         * @returns {RawTransactionV2}
```

**Review by calvinaco — APPROVED** [review]

File: lib/src/transaction/msg/gov/proposal/SoftwareUpgradeProposal.spec.ts (hunk 4 above)
Comment (calvinaco) [reply lib/src/transaction/msg/gov/proposal/SoftwareUpgradeProposal.spec.ts:146]: Sorry I mean in the original JSON there's
```
"upgradedClientState": { "typeUrl": "someTypeUrl", "value": "someValue"}
```

But in the parsed version you expect it to be undefined.

**Review by crypto-3dd — APPROVED** [review]
LGTM

File: lib/src/transaction/msg/gov/proposal/SoftwareUpgradeProposal.spec.ts (hunk 4 above)
Comment (cdc-Hitesh) [reply lib/src/transaction/msg/gov/proposal/SoftwareUpgradeProposal.spec.ts:146]: As discussed keeping the TODO. I will add a throw statement here.

File: lib/src/transaction/msg/gov/proposal/SoftwareUpgradeProposal.spec.ts [hunk 8]
```diff
@@ -127,5 +127,30 @@ describe('Testing SoftwareUpgradeProposal and its content types', function () {
 
             expect(SoftwareUpgradeProposal.description).to.eql('Lorem Ipsum ... Checking text proposal');
         });
+        it('should set `upgradedClientState` as undefined when non-empty', function () {
```
Comment (calvinaco) [inline lib/src/transaction/msg/gov/proposal/SoftwareUpgradeProposal.spec.ts:130]:
```suggestion
        it('should throw when `upgradedClientState` is non-empty', function () {
```

**Review by calvinaco — APPROVED** [review]
