### PR TITLE
Problem: Bug MsgTransfer NFT remove extra properties

### LINKED ISSUE #222: Problem: Remove extra properties from NFT MsgTransfer type

### PR DESCRIPTION
**Pull request by cdc-Hitesh**
Fixes #222

### CODE REVIEW

File: lib/src/transaction/msg/nft/MsgTransferNFT.ts [hunk 1]
```diff
@@ -59,13 +47,10 @@ export const msgTransferNFT = function (config: InitConfigurations) {
...
                 value: {
                     id: this.id,
-                    name: this.name,
                     sender: this.sender,
                     denomId: this.denomId,
-                    uri: this.uri,
-                    data: this.data,
                     recipient: this.recipient,
-                },
+                } as MsgTransferNFTOptions,
```
Comment (calvinaco) [inline lib/src/transaction/msg/nft/MsgTransferNFT.ts:53]: Why do we need this type hint here?

Comment (cdc-Hitesh) [reply lib/src/transaction/msg/nft/MsgTransferNFT.ts:53]: I want to ensure we are passing exactly what we are expecting. At least the compiler saves us from an innocent human error in the values.

**Review by calvinaco — APPROVED** [review]
